services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: integrador
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5437:5432'